# Generated by Django 4.2.6 on 2023-10-16 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('counsellorID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('counsellorName', models.TextField(max_length=50)),
                ('counsellorPhone', models.TextField(max_length=50)),
                ('counsellorEmail', models.TextField(max_length=50)),
                ('counsellorPassword', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField(max_length=50)),
                ('counsellorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.counsellor')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('studentName', models.TextField(max_length=50)),
                ('studentPhone', models.TextField(max_length=50)),
                ('studentEmail', models.TextField(max_length=50)),
                ('studentPassword', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(max_length=20)),
                ('counsellorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.counsellor')),
                ('sessionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.session')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.student')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.student'),
        ),
    ]
