# Generated by Django 4.2.6 on 2023-10-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracking',
            old_name='counsellorName',
            new_name='counsellorID',
        ),
        migrations.RemoveField(
            model_name='session',
            name='counsellorName',
        ),
        migrations.RemoveField(
            model_name='session',
            name='studentID',
        ),
        migrations.AddField(
            model_name='session',
            name='studentName',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
