# Generated by Django 4.2.6 on 2023-10-16 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_counsellorname_tracking_counsellorid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='studentName',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='counsellorID',
        ),
        migrations.AddField(
            model_name='session',
            name='studentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.student'),
        ),
    ]
