# Generated by Django 4.2.6 on 2023-10-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_session_studentname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.TextField(default='pending', max_length=20),
        ),
    ]
