# Generated by Django 4.2.6 on 2023-10-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_session_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='status',
        ),
        migrations.AddField(
            model_name='tracking',
            name='details',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tracking',
            name='followup',
            field=models.TextField(default='No', max_length=10),
        ),
    ]
