# Generated by Django 4.2.6 on 2023-10-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tracking',
        ),
    ]
