# Generated by Django 4.2.6 on 2023-10-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_delete_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.TextField(default='Pending', max_length=20),
        ),
    ]
