# Generated by Django 4.2.6 on 2023-10-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='followup',
            field=models.TextField(max_length=10),
        ),
    ]
